### ISSUE TITLE
Notify PR author if it becomes not mergeable

### ISSUE THREAD

**Issue by gabro** [buildo/nemobot#102]
## requirements
Sometimes a PR needs a rebase (because something was merged on master in the meanwhile) but the author didn't notice it. This slows down the review process, as the reviewer now needs to ask for a rebase and wait for it to happen.

It would be lovely if nemobot could promptly warn the PR author that the PR now needs a rebase 

## specs
Still not 100% confident this is doable, but I assume a PR event is triggered via webhook whenever the PR status changes from mergeable to not mergeable.

At that point we just need to check whether the PR is assigned and notify the author by posting a message on GitHub.

**Comment by FrancescoCioria** [comment]
we can use the [pullrequestevent](https://developer.github.com/v3/activity/events/types/#pullrequestevent) with `action: synchronize `which is triggered anytime a PR receives a new commit: if the key`mergeable` is `false` and PR is assigned -->post comment

**Comment by gabro** [comment]
nice
