### ISSUE TITLE
enforce basic set of labels in all repos

### ISSUE THREAD

**Issue by lucacioria** [buildo/nemobot#111]
## stories
- as a developer, I want to find my typical labels available in all repos so as to do things as I'm used to without effort
- as a PM, I want to find my typical labels available in all repos so as to have a clean and understandable repo where devs use the appropriate labels

## requirements
**current scenario:**
- we use a set of labels that is different from the default GitHub one
  - there might be overlap between the two (`bug`)
- we do not want certain labels to exist (`enhancement`)
- in every repo, in particular complex ones, there might be more labels specific to that repo

**objective**
- nemobot enforces that
  - all labels in the list `mustExist` are present and have a standard color assigned:
    - `bug`, `defect`, `DX`, `discussion`, `documentation`
    - nemobot labels: `macro`, `in review`, `WIP` (these should be enforced by nemobot code)
    - PRISMA labels: `customer`, priority labels, .. (these should be enforced by PRISMA code)
  - all labels in the list `mustNotExist` are not present

## specs
add task triggered by **any** event where:
- get list of repo labels
- filter labels that are missing/have wrong color
  - add missing labels
  - update labels with wrong color

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
@lucacioria nemobot and prisma work through webhooks, is it enough to enforce this only once when the two bots receive the first fake event github sends to new webhooks?

PS: no need to worry about nemobot/prisma crashing because one of their labels is missing: when you add a label to an issue/pr from API if the label does not exist yet it's automatically created by GitHub

**Comment by lucacioria** [comment]
perfect, if that's the case then we only need to enforce the other labels

**Comment by FrancescoCioria** [comment]
> is it enough to enforce this only once when the two bots receive the first fake event github sends to new webhooks?

@lucacioria ^

**Comment by lucacioria** [comment]
I don't understand pros and cons of this choice, either you make a choice that you think is the right one, or you make me understand :)

**Comment by FrancescoCioria** [comment]
nevermind, I'll do this:
anytime @nemobot receives a webhook (whatever "event" it is) it will enforce the labels on that repo.

same for prisma
