### ISSUE TITLE
Integrate new "reviewer" API with PR's "assignee" concept

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/nemobot#133]
## user story
**finally** "reviewers" have a real API: https://github.com/blog/2306-filter-pull-request-reviews-and-review-requests

`nemobot` is currently using the presence of a PR assignee to understand if the PR is being reviewed or is in WIP.

People have asked many times to use "reviewers" and some have already used it (even if it wasn't supported by any of buildo's tools...). Now that we can use the "reviewers" we should think of a new review-process and improve nemobot's logic to reflect it.

## requirements
We should separate the merger from the reviewers by saying that if a PR:
- has no "assignee"
  - it will be up to the creator to merge it (after its approval of course) or re-assign it to someone  else to delegate the merge
- has an "assignee"
  - it will be merged by the "assignee" after **every** reviewer has approved the PR
  - if the assignee is not also a reviewer
    - they are not required to do a review: if PR is approved they can merge it without formal approval

## specs
- PR state
  - WIP
    - there is no "reviewer"
  - in review (waiting for approvals)
    - there is **at least** a reviewer who has not yet approved it
  - waiting for merge
    - every reviewer has approved it
      - we could add a new label "waiting for merge"
  - merged
    - remove every state label (WIP/in review/waiting for merge)
- notifications
  - test plan
    - check for test plan when creator adds the first reviewer (when PR transitions from "WIP" to "in review")

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
### ANALYSIS
A PR has three main types of characters that may interact with it:
- PR's creator
- reviewer(s)
- merger

So far we never had a clear distinction between reviewers and merger as we had only one tag: "assignee"

Now, if we want to, we could associate the concept of "merger" to "assignee".

In buildo we don't have strict guidelines on who should merge a PR: it may be the creator, the reviewer or some other person.

### PROPOSAL
We could separate the merger from the reviewers by saying that if a PR:
- has no "assignee"
  - it will be apt to the the creator to merge it (after its approval of course) or re-assign it to someone  else to delegate the merge
- has an "assignee"
  - it will be merged by the "assignee" after **every** reviewer has approved the PR
  - if the assignee is not also a reviewer
    - they are not required to do a review: if PR is approved they can merge it without formal approval

### DRAFT OF SPECS
If we go with this proposal `nemobot`'s logic may be changed as follows:

- PR state
  - WIP
    - there is no "reviewer"
  - in review
    - there is at least a reviewer that has not yet accepted it
  - waiting for merge
    - every reviewer has approved it
      - we could add a new label "waiting for merge"
  - merged
    - remove every state label (WIP/in review/waiting for merge)

NOTE: this means that after the creator adds a "reviewer" that PR will never come back to "WIP" again (currently if you remove the "assignee" it goes back to WIP)

- notifications
  - test plan
    - check for test plan when creator adds the **first** reviewer (when PR transitions from "WIP" to "in review")

one last thing: what happens if the PR is merged by someone who's not the assignee nor the creator? should `nemobot` write a comment? or maybe re-assign the PR to the one who merged? or nothing?

**Comment by francescogior** [comment]
Overall great! But
> NOTE: this means that after the creator adds a "reviewer" that PR will never come back to "WIP" again (currently if you remove the "assignee" it goes back to WIP)

I guess the API supports the state of 'reviewers requested changes'. This should be mapped to the label "WIP" (and if there is an assignee, it could be automatically removed)

**Comment by FrancescoCioria** [comment]
> I guess the API supports the state of 'reviewers requested changes'. This should be mapped to the label "WIP"

👍 

>  (and if there is an assignee, it could be automatically removed)

why? the two things are not related, the assignee remains the delegated merger even if the PR has not yet been approved. He will simply have to wait until every reviewer has approved it.
When the dev is ready for a new he will require a new review from the same or another reviewer, that's should be enough as notification.

**Comment by francescogior** [comment]
> why? the two things are not related, the assignee remains the delegated merger even if the PR has not yet been approved. He will simply have to wait until every reviewer has approved it.

👍

**Comment by ascariandrea** [comment]
I agree with this flow since I'm one of the people who used it without guideline 🙈 
I have a question:
- how does the assignee know when all the reviewers approved a PR? Is there a github email for this?

We have now separate the 'review' step from the 'merge' one: can we introduce the possibility to rewrite commit history between the 2 steps?

**Comment by giogonzo** [comment]
We'd need a way to automatically check that there's no diff between pre and
post rewrite.. I'm conceptually in favor of an history cleanup
(documentation for later), but I don't want to risk merging broken stuff,
and this currently can only be done manually I think

**Comment by ascariandrea** [comment]
I'm aware of this.
Maybe it's something we can easily integrate with `hophop`. After reviewers' approvals we can use a `hophop pr-rewrite` to rewrite the history, keeping the old branch as reference and automatically check the new history doesn't introduce new changes.

Anyway this is out of scope for now, just think about this.
