### ISSUE TITLE
backup issues to S3

### ISSUE THREAD

**Issue by lucacioria** [buildo/nemobot#14]
as a safe feature, backup everything every hour maybe? This is relevant mostly because descriptions and comments do not have history in github, so if we mistakenly delete something.. it's lost!

**Comment by FrancescoCioria** [comment]
labonline is already being backed up every day

**Comment by gabro** [comment]
actually, every hour.

**Comment by gabro** [comment]
Just for reference, GitHub is now sending webhooks for editing titles and descriptions.

Not sure how this issue is affected, but it feels relevant somehow

**Comment by FrancescoCioria** [comment]
bye bye
