### ISSUE TITLE
find a better name

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/nemobot#45]
## requirements
`github-prettifier` is confusing as it doesn't explain what is the real purpose of this project.
I suggest we rename our bots/enhancement projects with clearer name which explains its area of action or, for the bots, which reflects its bot name

## specs
- nemobot?
- github-worker?

## misc
We should not only change the name but also make clear that anything concerning an action on GitHub **triggered by an event** and **made by a bot** should be done on this repo and by @nemobot .
(In the same way we should create/edit any repo for other bots like slack bots, raven bot etc..)

If you think this issue is too generic for this repo let's move it to infra/universe/whatever

@gabro

**Comment by gabro** [comment]
I'm all for `nemobot`!

![44](https://cloud.githubusercontent.com/assets/691940/14232383/08783d02-f978-11e5-94d4-4535ac9db905.png)

**Comment by gabro** [comment]
Rebranded to nemobot!

Also, I've setup a dns record https://nemobot.our.buildo.io and updated the webhook integration of:
- buildo/nemobot
- buildo/aliniq
- buildo/react-components

other repos to update, @FrancescoCioria?
