### ISSUE TITLE
[reminder] remind test-plan when PR is assigned

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/nemobot#63]
## requirements
When a PR is assigned, if it is missing the test-plan, nemobot should **immediately** remind the creator to add one

## specs
- PR is assigned
  - does it contain `{PRTemplate}`? (without the Issue pointer part)
    - no --> ok
    - yes ---> add comment reminding the creator to add one

**Comment by gabro** [comment]
as discussed offline, big 👍
