### ISSUE TITLE
[server] move issue template logic to nemobot

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/nemobot#64]
## requirements
`github-workflow-pal` shouldn't fetch templates and compute the issue url: this logic should be moved to nemobot.
why:
- once the templates are moved to this repo nemobot can have direct access to them
  - no longer relying on rawgit (which went down one day in the last month)
- `prisma` can use these templates too without duplicating the logic
- updating nemobot is easier than publishing a new version of `g-w-p` on the chrome store

## specs
add four GET, one for each template:
- GET `/templateQueries
  - /bug
  - /defect
  - /feature
  - /standard
- return json with template fields and computed query
ex:
```json
"data": {
  "template": {
    "title": "[{topic}] {title}",
    "titleSelection": "{topic}",
    ...
  },
  "computedQuery": "labels=&title=[{topic}]%20{title}&titleSelection={topic}"
```

**Comment by gabro** [comment]
Not sure about the specs.

How about we define a single API endpoint

`/issueTypes`

so that the extension has even less logic? This might also enable the server to return the appropriate issue types for the repo

**Comment by FrancescoCioria** [comment]
> This might also enable the server to return the appropriate issue types for the repo

I wanted to keep the logic small for now: enabling templates based on repo doesn't seem strictly necessary for now

I'm not against having only endpoint, but that would actually increase the logic on the extension as it will have to "remember" which button the user clicked in order to get the correct template from the returned json

**Comment by gabro** [comment]
I don't remember the implementation details of the extension, so whatever it's simpler, go for it
