### ISSUE TITLE
Notify PR reviewers on slack 

### ISSUE THREAD

**Issue by gabro** [buildo/nemobot#7]
Draft idea: nudge PR reviewers with a private message on slack, sometimes after the assignment (6hours, 1day?)

Why?
Honestly, because I forget to review PRs assigned to me. GitHub is too "noisy" to actively remember me that I have assigned PRs.

Thoughts? @buildo/everyone?

**Comment by francescogior** [comment]
Like it, I think I'd be very useful for us.
For the times, I think something like:
- after 5 mins
- after 1h
- then every day at, say, 10am, 2.30pm, 5.30pm

**Comment by lucacioria** [comment]
+1
in general a notification system on the prettifier (which has to change name ASAP :p) seems interesting for:
- reminders (developers, PM)
- tracking progress (PM)

slack seems a good solution here, more flexible than email.
How is the API integration going to work?

**Comment by gabro** [comment]
I briefly went through the slack API. It should be as easy as an incoming webhook that posts DMs (https://twitter.com/slackapi/status/508355781889384449?lang=en)

Big question is: if we have to store it, where should we save the information?
Could it be the first time we start inserting hidden metadata into issue/pr descriptions?

**Comment by FrancescoCioria** [comment]
:+1: (poor @giogonzo will receive even more notifications! :P)

**Comment by FrancescoCioria** [comment]
> nudge PR reviewers with a private message on slack, sometimes after the assignment (6hours, 1day?)

After the switch to GitHub webhooks this has become trickier as we have to store somewhere the information about open&assigned PRs and update it at each received webhook

**Comment by giogonzo** [comment]
> (poor @giogonzo will receive even more notifications! :P)

MUTE

**Comment by gabro** [comment]
Relevant to this issue: we're partially tackling this with https://github.com/buildo/infra/tree/master/scripts/github/pr-to-review

**Comment by FrancescoCioria** [comment]
@gabro do still see this as a big pain-point or is pr-to-review enough for the moment? if it's enough I would close this issue

**Comment by gabro** [comment]
Closing. I'll gather more data and re-open it if it looks like a pain point
