### ISSUE TITLE
[macro] add feature to split macro issues

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/nemobot#74]
## requirements

**ability to move all open sub-issues to a new macro issue automatically**

sometimes we overload macro issues till the point where we want to split in two:
1) macro issue with all closed sub-issue (this macro issue will then be closed)
2) macro issue with all **open** sub-issue

this is useful to remove noise and concentrate on smaller tasks

## specs
- add `POST /splitMacroIssue/${macroIssueNumber}`
  - update macro issue body
    - remove open sub-issues from `sub-issues` paragraph
  - create new macro issue
    - create new issue (TODO: which title? which body? labels? ...)
    - get newly created issue number
    - create `sub-issues` paragraph
    - update every open-subissue
      - replace oldParentIssueNumber with new one

## misc
{optional: other useful info}

**Comment by lucacioria** [comment]
seems reasonable to me because it encourages to "close the current iteration" and open a new one if things got out of hand.

**Comment by gabro** [comment]
It's very aligned with our CoC, so +1 on this.

If you intend to also provide UI access to this, be sure to be *very* explicit on what it does.

**Comment by giogonzo** [comment]
```js
if (confirm('are you sure sure SURE?')) {
}
```

**Comment by FrancescoCioria** [comment]
@giogonzo pointed out that the current specs would cause conflicts with `prisma`:
if the the macro issue is also a customer issue (and most customer issues are currently macro) than `prisma` would move the card to `done` (as the original macro would be closed).

offline with @giogonzo I proposed to improve the current specs to split the original macro in three:
1) macro issue with open sub-issues pointing to original macro
2) macro issue with closed sub-issues pointing to original macro
3) original macro with 1 and 2 as sub-issues (1 is open, 2 is closed -> 3 is therefore still open)

I know having deep levels of macro issue increase management complexity, but nevertheless sometimes the advantages (see requirements) are worth it, especially we're talking of customer issues (I'd rather have two-levels deep macro issues than misunderstandings with the customer on what we've actually accomplished)

@lucacioria @gabro ^

**Comment by gabro** [comment]
sounds like a solid proposal. 👍
